# Generated by Django 6.0.6 on 2026-07-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('nop', models.IntegerField(default=0)),
                ('isbn', models.CharField(max_length=100)),
                ('publish_year', models.IntegerField()),
                ('cover_image', models.ImageField(upload_to='books/')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.genre')),
            ],
        ),
    ]
